import { ShiftType } from "../../type";

export const mockShifts: ShiftType[] = [
  {
    id: 1,
    station: 1,
    assign_user: 101,
    pre_shift: null,
    next_shift: 2,
    start_time: "08:00",
    end_time: "10:00",
    shift_number: 1,
    infor_exist: 201,
    infor_during: 202,
    infor_pre: 203,
    status: "completed",
    approved: true,
    note: "Night shift completed smoothly",
    create_user: 101,
  },
  {
    id: 2,
    station: 1,
    assign_user: 102,
    pre_shift: 1,
    next_shift: 3,
    start_time: "08:00",
    end_time: "10:00",
    shift_number: 2,
    infor_exist: 202,
    infor_during: 203,
    infor_pre: 204,
    status: "in-progress",
    approved: false,
    note: "Morning shift delayed",
    create_user: 102,
  },
  {
    id: 3,
    station: 1,
    assign_user: 103,
    pre_shift: 2,
    next_shift: 4,
    start_time: "08:00",
    end_time: "10:00",
    shift_number: 3,
    infor_exist: 203,
    infor_during: 204,
    infor_pre: 205,
    status: "pending",
    approved: false,
    note: "Evening shift waiting for approval",
    create_user: 103,
  },
];
