export enum MUTATION_KEY {
  CREATE_SHIFT_FOLLOW_DAY = "CREATE_SHIFT_FOLLOW_DAY",
  UPDATE_SHIFT_FOLLOW_DAY = "UPDATE_SHIFT_FOLLOW_DAY",
  UPDATE_SHIFT_FOLLOW_DAY_FORM_DATA = "UPDATE_SHIFT_FOLLOW_DAY_FORM_DATA",
  SIGN_IN = "SIGN_IN",
}
