export enum QUERY_KEY {
  GET_ALL_STATION = "GET_ALL_STATION",
  GET_ALL_SHIFT = "GET_ALL_SHIFT",
  GET_ALL_SHIFT_ORDER_BY_DATE = "GET_ALL_SHIFT_ORDER_BY_DATE",
  GET_ALL_MEMBER = "GET_ALL_MEMBER",
  ME = "ME",
}
